project:
  type: website
  output-dir: docs
  resources:
    - assets/papers/neppcrb2202.pdf
    - assets/resume.pdf

website:
  title: "Nicholas Chiumenti"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: 404.qmd
        text: Public
      - href: 404.qmd
        text: Projects
      - href: resume.qmd
        text: Resume/CV

format:
  html:
    grid:
      sidebar-width: 100px
      body-width: 1000px
      margin-width: 100px
      gutter-width: 1.5rem
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




