project:
  type: website
  output-dir: docs

website:
  title: "Nicholas Chiumenti"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: 404.qmd
        text: Research
      - href: 404.qmd
        text: Public
      - href: 404.qmd
        text: Projects
      - href: 404.qmd
        text: Resume/CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



